# Generated by Django 3.2.9 on 2021-12-04 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gb_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='greatbuilding',
            name='level',
        ),
        migrations.RemoveField(
            model_name='greatbuilding',
            name='p1',
        ),
        migrations.RemoveField(
            model_name='greatbuilding',
            name='p2',
        ),
        migrations.RemoveField(
            model_name='greatbuilding',
            name='p3',
        ),
        migrations.RemoveField(
            model_name='greatbuilding',
            name='p4',
        ),
        migrations.RemoveField(
            model_name='greatbuilding',
            name='p5',
        ),
        migrations.CreateModel(
            name='GBLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=1)),
                ('p1', models.IntegerField(default=0)),
                ('p2', models.IntegerField(default=0)),
                ('p3', models.IntegerField(default=0)),
                ('p4', models.IntegerField(default=0)),
                ('p5', models.IntegerField(default=0)),
                ('gb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gb_app.greatbuilding')),
            ],
        ),
    ]
