# Generated by Django 3.2.9 on 2021-12-04 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gb_app', '0002_auto_20211204_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gblevel',
            name='gb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gb_level', to='gb_app.greatbuilding'),
        ),
    ]
